appVersion: "2.0"

image:
  repository: fhdoai/sose-pacman-frontend
  tag: "latest"
  pullPolicy: IfNotPresent

replicaCount: 2

containerPort: 80

service:
  type: ClusterIP
  port: 80
  targetPort: 80
