apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pacman-svc
  labels:
    app: {{ .Release.Name }}-pacman
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-pacman
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
